{% set name = "kedro-pandera" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro_pandera-{{ version }}.tar.gz
  sha256: f8ea0768c2525a63b397c410151973a6bcfd6739cc2606fcff2430e40e32548b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools-scm
    - pip
  run:
    - python >=3.8,<3.12
    - pandera >=0.15
    - kedro >=0.18.13,<0.19

test:
  imports:
    - kedro_pandera
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Galileo-Galilei/kedro-pandera
  summary: A kedro plugin to use pandera in your kedro projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
